spring:
  profiles:
    active:
      - dev
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  sql:
    init:
      mode: always

  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

      # mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.spring_demo.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
